namespace WareBaseMS
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using UI;

    public class frmCellPltSpec : FrmSTable
    {
        private ToolStripButton btn_M_Help;
        private CheckBox chkArea;
        private CheckedListBox chkListArea;
        private ComboBox cmb_cPltSpecId;
        private ComboBox cmb_cWHId;
        private DataGridViewTextBoxColumn colcArea;
        private DataGridViewTextBoxColumn colcPltSpec;
        private DataGridViewTextBoxColumn colcWHId;
        private IContainer components = null;
        public DataGridView grdList;
        private Label label1;
        private Label label2;
        private Label label3;
        private Panel pnlEdit;
        public ToolStripButton tlb_M_Check;
        public ToolStripButton tlb_M_Delete;
        public ToolStripButton tlb_M_Edit;
        private ToolStripButton tlb_M_Exit;
        public ToolStripButton tlb_M_Find;
        public ToolStripButton tlb_M_New;
        public ToolStripButton tlb_M_Print;
        public ToolStripButton tlb_M_Refresh;
        public ToolStripButton tlb_M_Save;
        private ToolStripButton tlb_M_UnCheck;
        public ToolStripButton tlb_M_Undo;
        public ToolStrip tlbMain;
        public ToolStripLabel toolStripLabel1;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripSeparator toolStripSeparator3;
        private ToolStripSeparator toolStripSeparator4;
        private ToolStripSeparator toolStripSeparator5;
        private ToolStripSeparator toolStripSeparator6;
        private ToolStripSeparator toolStripSeparator7;
        private ToolStripSeparator toolStripSeparator8;

        public frmCellPltSpec()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmCellPltSpec));
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.tlbMain = new ToolStrip();
            this.toolStripLabel1 = new ToolStripLabel();
            this.toolStripSeparator2 = new ToolStripSeparator();
            this.toolStripSeparator1 = new ToolStripSeparator();
            this.tlb_M_New = new ToolStripButton();
            this.tlb_M_Edit = new ToolStripButton();
            this.toolStripSeparator3 = new ToolStripSeparator();
            this.tlb_M_Undo = new ToolStripButton();
            this.tlb_M_Delete = new ToolStripButton();
            this.toolStripSeparator4 = new ToolStripSeparator();
            this.tlb_M_Save = new ToolStripButton();
            this.toolStripSeparator5 = new ToolStripSeparator();
            this.tlb_M_Refresh = new ToolStripButton();
            this.tlb_M_Find = new ToolStripButton();
            this.tlb_M_Print = new ToolStripButton();
            this.toolStripSeparator6 = new ToolStripSeparator();
            this.tlb_M_Check = new ToolStripButton();
            this.tlb_M_UnCheck = new ToolStripButton();
            this.toolStripSeparator7 = new ToolStripSeparator();
            this.btn_M_Help = new ToolStripButton();
            this.tlb_M_Exit = new ToolStripButton();
            this.toolStripSeparator8 = new ToolStripSeparator();
            this.pnlEdit = new Panel();
            this.cmb_cWHId = new ComboBox();
            this.label3 = new Label();
            this.cmb_cPltSpecId = new ComboBox();
            this.label2 = new Label();
            this.label1 = new Label();
            this.chkArea = new CheckBox();
            this.chkListArea = new CheckedListBox();
            this.grdList = new DataGridView();
            this.colcWHId = new DataGridViewTextBoxColumn();
            this.colcPltSpec = new DataGridViewTextBoxColumn();
            this.colcArea = new DataGridViewTextBoxColumn();
            this.tlbMain.SuspendLayout();
            this.pnlEdit.SuspendLayout();
            ((ISupportInitialize) this.grdList).BeginInit();
            base.SuspendLayout();
            this.tlbMain.Items.AddRange(new ToolStripItem[] { 
                this.toolStripLabel1, this.toolStripSeparator2, this.toolStripSeparator1, this.tlb_M_New, this.tlb_M_Edit, this.toolStripSeparator3, this.tlb_M_Undo, this.tlb_M_Delete, this.toolStripSeparator4, this.tlb_M_Save, this.toolStripSeparator5, this.tlb_M_Refresh, this.tlb_M_Find, this.tlb_M_Print, this.toolStripSeparator6, this.tlb_M_Check, 
                this.tlb_M_UnCheck, this.toolStripSeparator7, this.btn_M_Help, this.tlb_M_Exit, this.toolStripSeparator8
             });
            this.tlbMain.Location = new Point(0, 0);
            this.tlbMain.Name = "tlbMain";
            this.tlbMain.Size = new Size(0x313, 0x19);
            this.tlbMain.TabIndex = 7;
            this.tlbMain.Text = "toolStrip1";
            this.toolStripLabel1.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.toolStripLabel1.ForeColor = SystemColors.ActiveCaption;
            this.toolStripLabel1.Name = "toolStripLabel1";
            this.toolStripLabel1.Size = new Size(0, 0x16);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new Size(6, 0x19);
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new Size(6, 0x19);
            this.tlb_M_New.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_New.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_New.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_New.Image = (Image) manager.GetObject("tlb_M_New.Image");
            this.tlb_M_New.ImageTransparentColor = Color.Magenta;
            this.tlb_M_New.Name = "tlb_M_New";
            this.tlb_M_New.Size = new Size(0x23, 0x16);
            this.tlb_M_New.Tag = "01";
            this.tlb_M_New.Text = "新建";
            this.tlb_M_New.Visible = false;
            this.tlb_M_Edit.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Edit.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Edit.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Edit.Image = (Image) manager.GetObject("tlb_M_Edit.Image");
            this.tlb_M_Edit.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Edit.Name = "tlb_M_Edit";
            this.tlb_M_Edit.Size = new Size(0x23, 0x16);
            this.tlb_M_Edit.Tag = "02";
            this.tlb_M_Edit.Text = "修改";
            this.tlb_M_Edit.Click += new EventHandler(this.tlb_M_Edit_Click);
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new Size(6, 0x19);
            this.tlb_M_Undo.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Undo.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Undo.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Undo.Image = (Image) manager.GetObject("tlb_M_Undo.Image");
            this.tlb_M_Undo.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Undo.Name = "tlb_M_Undo";
            this.tlb_M_Undo.Size = new Size(0x23, 0x16);
            this.tlb_M_Undo.Tag = "03";
            this.tlb_M_Undo.Text = "取消";
            this.tlb_M_Delete.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Delete.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Delete.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Delete.Image = (Image) manager.GetObject("tlb_M_Delete.Image");
            this.tlb_M_Delete.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Delete.Name = "tlb_M_Delete";
            this.tlb_M_Delete.Size = new Size(0x23, 0x16);
            this.tlb_M_Delete.Tag = "04";
            this.tlb_M_Delete.Text = "删除";
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new Size(6, 0x19);
            this.tlb_M_Save.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Save.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Save.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Save.Image = (Image) manager.GetObject("tlb_M_Save.Image");
            this.tlb_M_Save.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Save.Name = "tlb_M_Save";
            this.tlb_M_Save.Size = new Size(0x23, 0x16);
            this.tlb_M_Save.Tag = "05";
            this.tlb_M_Save.Text = "保存";
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new Size(6, 0x19);
            this.tlb_M_Refresh.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Refresh.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Refresh.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Refresh.Image = (Image) manager.GetObject("tlb_M_Refresh.Image");
            this.tlb_M_Refresh.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Refresh.Name = "tlb_M_Refresh";
            this.tlb_M_Refresh.Size = new Size(0x23, 0x16);
            this.tlb_M_Refresh.Text = "刷新";
            this.tlb_M_Find.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Find.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Find.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Find.Image = (Image) manager.GetObject("tlb_M_Find.Image");
            this.tlb_M_Find.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Find.Name = "tlb_M_Find";
            this.tlb_M_Find.Size = new Size(0x23, 0x16);
            this.tlb_M_Find.Text = "查找";
            this.tlb_M_Find.Visible = false;
            this.tlb_M_Print.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Print.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Print.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Print.Image = (Image) manager.GetObject("tlb_M_Print.Image");
            this.tlb_M_Print.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Print.Name = "tlb_M_Print";
            this.tlb_M_Print.Size = new Size(0x23, 0x16);
            this.tlb_M_Print.Tag = "06";
            this.tlb_M_Print.Text = "打印";
            this.tlb_M_Print.Visible = false;
            this.toolStripSeparator6.Name = "toolStripSeparator6";
            this.toolStripSeparator6.Size = new Size(6, 0x19);
            this.tlb_M_Check.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Check.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Check.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Check.Image = (Image) manager.GetObject("tlb_M_Check.Image");
            this.tlb_M_Check.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Check.Name = "tlb_M_Check";
            this.tlb_M_Check.Size = new Size(0x23, 0x16);
            this.tlb_M_Check.Tag = "7";
            this.tlb_M_Check.Text = "审核";
            this.tlb_M_Check.Visible = false;
            this.tlb_M_UnCheck.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_UnCheck.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_UnCheck.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_UnCheck.Image = (Image) manager.GetObject("tlb_M_UnCheck.Image");
            this.tlb_M_UnCheck.ImageTransparentColor = Color.Magenta;
            this.tlb_M_UnCheck.Name = "tlb_M_UnCheck";
            this.tlb_M_UnCheck.Size = new Size(0x3d, 0x16);
            this.tlb_M_UnCheck.Tag = "08";
            this.tlb_M_UnCheck.Text = "取消审核";
            this.tlb_M_UnCheck.Visible = false;
            this.toolStripSeparator7.Name = "toolStripSeparator7";
            this.toolStripSeparator7.Size = new Size(6, 0x19);
            this.btn_M_Help.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.btn_M_Help.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.btn_M_Help.ForeColor = SystemColors.ActiveCaption;
            this.btn_M_Help.Image = (Image) manager.GetObject("btn_M_Help.Image");
            this.btn_M_Help.ImageTransparentColor = Color.Magenta;
            this.btn_M_Help.Name = "btn_M_Help";
            this.btn_M_Help.Size = new Size(0x23, 0x16);
            this.btn_M_Help.Text = "帮助";
            this.tlb_M_Exit.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Exit.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Exit.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Exit.Image = (Image) manager.GetObject("tlb_M_Exit.Image");
            this.tlb_M_Exit.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Exit.Name = "tlb_M_Exit";
            this.tlb_M_Exit.Size = new Size(0x23, 0x16);
            this.tlb_M_Exit.Text = "退出";
            this.toolStripSeparator8.Name = "toolStripSeparator8";
            this.toolStripSeparator8.Size = new Size(6, 0x19);
            this.pnlEdit.Controls.Add(this.cmb_cWHId);
            this.pnlEdit.Controls.Add(this.label3);
            this.pnlEdit.Controls.Add(this.cmb_cPltSpecId);
            this.pnlEdit.Controls.Add(this.label2);
            this.pnlEdit.Controls.Add(this.label1);
            this.pnlEdit.Controls.Add(this.chkArea);
            this.pnlEdit.Controls.Add(this.chkListArea);
            this.pnlEdit.Location = new Point(0x15f, 0x4e);
            this.pnlEdit.Name = "pnlEdit";
            this.pnlEdit.Size = new Size(0x1a8, 0x1b9);
            this.pnlEdit.TabIndex = 9;
            this.cmb_cWHId.FormattingEnabled = true;
            this.cmb_cWHId.Location = new Point(0x67, 0x4b);
            this.cmb_cWHId.Name = "cmb_cWHId";
            this.cmb_cWHId.Size = new Size(0xb3, 20);
            this.cmb_cWHId.TabIndex = 14;
            this.cmb_cWHId.Tag = "101";
            this.cmb_cWHId.Text = "Bind SelectedValue";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(0x20, 0x4e);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x29, 12);
            this.label3.TabIndex = 13;
            this.label3.Text = "仓库：";
            this.cmb_cPltSpecId.FormattingEnabled = true;
            this.cmb_cPltSpecId.Location = new Point(0x67, 0x27);
            this.cmb_cPltSpecId.Name = "cmb_cPltSpecId";
            this.cmb_cPltSpecId.Size = new Size(0xb3, 20);
            this.cmb_cPltSpecId.TabIndex = 12;
            this.cmb_cPltSpecId.Tag = "101";
            this.cmb_cPltSpecId.Text = "Bind SelectedValue";
            this.label2.AutoSize = true;
            this.label2.Location = new Point(0x20, 0x2a);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x41, 12);
            this.label2.TabIndex = 6;
            this.label2.Text = "托盘规格：";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(0x20, 0x7b);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x29, 12);
            this.label1.TabIndex = 4;
            this.label1.Text = "货区：";
            this.chkArea.AutoSize = true;
            this.chkArea.Location = new Point(0x67, 0x185);
            this.chkArea.Name = "chkArea";
            this.chkArea.Size = new Size(0x30, 0x10);
            this.chkArea.TabIndex = 2;
            this.chkArea.Text = "全选";
            this.chkArea.UseVisualStyleBackColor = true;
            this.chkListArea.FormattingEnabled = true;
            this.chkListArea.Location = new Point(0x67, 0x72);
            this.chkListArea.Name = "chkListArea";
            this.chkListArea.Size = new Size(0xb3, 260);
            this.chkListArea.TabIndex = 0;
            this.grdList.AllowUserToAddRows = false;
            this.grdList.AllowUserToDeleteRows = false;
            this.grdList.AllowUserToOrderColumns = true;
            this.grdList.Columns.AddRange(new DataGridViewColumn[] { this.colcWHId, this.colcPltSpec, this.colcArea });
            this.grdList.EditMode = DataGridViewEditMode.EditProgrammatically;
            this.grdList.Location = new Point(12, 0x4e);
            this.grdList.MultiSelect = false;
            this.grdList.Name = "grdList";
            this.grdList.ReadOnly = true;
            style.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            this.grdList.RowHeadersDefaultCellStyle = style;
            this.grdList.RowHeadersVisible = false;
            this.grdList.RowTemplate.Height = 0x17;
            this.grdList.Size = new Size(0x14d, 0x1b9);
            this.grdList.TabIndex = 10;
            this.grdList.Tag = "8";
            this.colcWHId.DataPropertyName = "cWHId";
            this.colcWHId.FillWeight = 50f;
            this.colcWHId.Frozen = true;
            this.colcWHId.HeaderText = "仓库号";
            this.colcWHId.Name = "colcWHId";
            this.colcWHId.ReadOnly = true;
            this.colcWHId.ToolTipText = "仓库";
            this.colcWHId.Width = 110;
            this.colcPltSpec.DataPropertyName = "cPltSpec";
            this.colcPltSpec.HeaderText = "托盘规格";
            this.colcPltSpec.Name = "colcPltSpec";
            this.colcPltSpec.ReadOnly = true;
            this.colcPltSpec.ToolTipText = "托盘规格";
            this.colcPltSpec.Width = 120;
            this.colcArea.DataPropertyName = "cAreaName";
            this.colcArea.HeaderText = "货区";
            this.colcArea.Name = "colcArea";
            this.colcArea.ReadOnly = true;
            this.colcArea.ToolTipText = "货区";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(0x313, 0x28b);
            base.Controls.Add(this.grdList);
            base.Controls.Add(this.pnlEdit);
            base.Controls.Add(this.tlbMain);
            base.Name = "frmCellPltSpec";
            this.Text = "货区与托盘类型对应";
            this.tlbMain.ResumeLayout(false);
            this.tlbMain.PerformLayout();
            this.pnlEdit.ResumeLayout(false);
            this.pnlEdit.PerformLayout();
            ((ISupportInitialize) this.grdList).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private void tlb_M_Edit_Click(object sender, EventArgs e)
        {
            this.pnlEdit.Enabled = true;
        }
    }
}

