namespace WarehouseBase
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using UI;

    public class frmMatMappingList : FrmSTable
    {
        private ToolStripButton btn_M_Help;
        private Button btn_SelSupplier;
        private ComboBox cmb_bIsAutoBatchNo;
        private ComboBox cmb_bIsFromErp;
        private ComboBox cmb_bIsQc;
        private ComboBox cmb_bIsSubQtyForQC;
        private ComboBox cmb_cABC;
        private ComboBox cmb_cTypeId1;
        private ComboBox cmb_cTypeId2;
        private ComboBox cmb_cUnit;
        private ComboBox cmb_cWHId;
        private ComboBox cmb_nMatClass;
        private ComboBox cmb_nPlaceMode;
        private DataGridViewTextBoxColumn col_M_cMName;
        private DataGridViewTextBoxColumn col_M_cMNo;
        private ComboBox comboBox1;
        private IContainer components = null;
        private DataGridView dataGridView1;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn1;
        private DataGridViewTextBoxColumn dataGridViewTextBoxColumn2;
        private DataGridView grdMatList;
        private GroupBox grpCondition;
        private Label label1;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Label label14;
        private Label label15;
        private Label label16;
        private Label label17;
        private Label label18;
        private Label label19;
        private Label label2;
        private Label label20;
        private Label label21;
        private Label label22;
        private Label label23;
        private Label label24;
        private Label label25;
        private Label label26;
        private Label label27;
        private Label label28;
        private Label label29;
        private Label label3;
        private Label label30;
        private Label label31;
        private Label label32;
        private Label label33;
        private Label label34;
        private Label label35;
        private Label label36;
        private Label label37;
        private Label label38;
        private Label label39;
        private Label label4;
        private Label label40;
        private Label label41;
        private Label label42;
        private Label label43;
        private Label label44;
        private Label label45;
        private Label label48;
        private Label label5;
        private Label label55;
        private Label label56;
        private Label label6;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label lbl_M_Count;
        private Panel panel1;
        private Panel pnlListRecCount;
        private Panel pnlMatInfo;
        private SplitContainer spliterMain;
        private TabControl tbcMain;
        private TabPage tbp_ExProperty;
        private TabPage tbpMatInfo;
        private TextBox textBox_cBorCode;
        private TextBox textBox_cCreator;
        private TextBox textBox_cLinkId;
        private TextBox textBox_cMNo;
        private TextBox textBox_cName;
        private TextBox textBox_fDPSInQtyDn;
        private TextBox textBox_fDPSInQtyUp;
        private TextBox textBox_fQtyBox;
        private TextBox textBox_fSafeQtyDn;
        private TextBox textBox_fSafeQtyUp;
        private TextBox textBox_fWeight;
        private TextBox textBox_nAutoPromptDay;
        private TextBox textBox_nKeepDay;
        private TextBox textBox1;
        private TextBox textBox1_cSpec;
        private TextBox textBox2;
        public ToolStripButton tlb_M_Delete;
        public ToolStripButton tlb_M_Edit;
        private ToolStripButton tlb_M_Exit;
        public ToolStripButton tlb_M_Find;
        public ToolStripButton tlb_M_New;
        public ToolStripButton tlb_M_Print;
        public ToolStripButton tlb_M_Refresh;
        public ToolStripButton tlb_M_Save;
        public ToolStripButton tlb_M_Undo;
        public ToolStrip tlbMain;
        private ToolStripButton tlbSaveSysRts;
        public ToolStripLabel toolStripLabel1;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripSeparator toolStripSeparator3;
        private ToolStripSeparator toolStripSeparator4;
        private ToolStripSeparator toolStripSeparator5;
        private ToolStripSeparator toolStripSeparator6;
        private ToolStripSeparator toolStripSeparator7;
        private ToolStripSeparator toolStripSeparator8;
        private TextBox txt_cCSId;
        private TextBox txt_cMatOther;
        private TextBox txt_cMatQCLevel;
        private TextBox txt_cMatStyle;
        private TextBox txt_cRemark;
        private TextBox txt_cSupplier;
        private TextBox txt_nTag;

        public frmMatMappingList()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void frmMatMappingList_Load(object sender, EventArgs e)
        {
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmMatMappingList));
            this.tlbMain = new ToolStrip();
            this.toolStripLabel1 = new ToolStripLabel();
            this.toolStripSeparator2 = new ToolStripSeparator();
            this.toolStripSeparator1 = new ToolStripSeparator();
            this.tlb_M_New = new ToolStripButton();
            this.tlb_M_Edit = new ToolStripButton();
            this.toolStripSeparator3 = new ToolStripSeparator();
            this.tlb_M_Undo = new ToolStripButton();
            this.tlb_M_Delete = new ToolStripButton();
            this.toolStripSeparator4 = new ToolStripSeparator();
            this.tlb_M_Save = new ToolStripButton();
            this.toolStripSeparator5 = new ToolStripSeparator();
            this.tlb_M_Refresh = new ToolStripButton();
            this.tlb_M_Find = new ToolStripButton();
            this.tlb_M_Print = new ToolStripButton();
            this.toolStripSeparator6 = new ToolStripSeparator();
            this.toolStripSeparator7 = new ToolStripSeparator();
            this.btn_M_Help = new ToolStripButton();
            this.tlb_M_Exit = new ToolStripButton();
            this.toolStripSeparator8 = new ToolStripSeparator();
            this.tlbSaveSysRts = new ToolStripButton();
            this.spliterMain = new SplitContainer();
            this.grpCondition = new GroupBox();
            this.pnlListRecCount = new Panel();
            this.grdMatList = new DataGridView();
            this.label1 = new Label();
            this.lbl_M_Count = new Label();
            this.tbcMain = new TabControl();
            this.tbpMatInfo = new TabPage();
            this.tbp_ExProperty = new TabPage();
            this.col_M_cMNo = new DataGridViewTextBoxColumn();
            this.col_M_cMName = new DataGridViewTextBoxColumn();
            this.pnlMatInfo = new Panel();
            this.panel1 = new Panel();
            this.label2 = new Label();
            this.label3 = new Label();
            this.dataGridView1 = new DataGridView();
            this.dataGridViewTextBoxColumn1 = new DataGridViewTextBoxColumn();
            this.dataGridViewTextBoxColumn2 = new DataGridViewTextBoxColumn();
            this.label55 = new Label();
            this.cmb_nMatClass = new ComboBox();
            this.label56 = new Label();
            this.label48 = new Label();
            this.cmb_cABC = new ComboBox();
            this.label45 = new Label();
            this.txt_cRemark = new TextBox();
            this.txt_cCSId = new TextBox();
            this.txt_nTag = new TextBox();
            this.label44 = new Label();
            this.cmb_bIsAutoBatchNo = new ComboBox();
            this.label11 = new Label();
            this.btn_SelSupplier = new Button();
            this.label43 = new Label();
            this.txt_cMatOther = new TextBox();
            this.label42 = new Label();
            this.txt_cSupplier = new TextBox();
            this.txt_cMatQCLevel = new TextBox();
            this.label41 = new Label();
            this.txt_cMatStyle = new TextBox();
            this.label40 = new Label();
            this.label38 = new Label();
            this.textBox_nAutoPromptDay = new TextBox();
            this.label37 = new Label();
            this.cmb_bIsSubQtyForQC = new ComboBox();
            this.label36 = new Label();
            this.label31 = new Label();
            this.label32 = new Label();
            this.label29 = new Label();
            this.label28 = new Label();
            this.label27 = new Label();
            this.label30 = new Label();
            this.cmb_nPlaceMode = new ComboBox();
            this.cmb_bIsQc = new ComboBox();
            this.cmb_bIsFromErp = new ComboBox();
            this.cmb_cTypeId2 = new ComboBox();
            this.cmb_cTypeId1 = new ComboBox();
            this.cmb_cUnit = new ComboBox();
            this.cmb_cWHId = new ComboBox();
            this.textBox_fDPSInQtyUp = new TextBox();
            this.textBox_cLinkId = new TextBox();
            this.textBox_cBorCode = new TextBox();
            this.textBox_cCreator = new TextBox();
            this.textBox1_cSpec = new TextBox();
            this.textBox_fSafeQtyDn = new TextBox();
            this.textBox_fSafeQtyUp = new TextBox();
            this.textBox_nKeepDay = new TextBox();
            this.textBox_fQtyBox = new TextBox();
            this.textBox_fDPSInQtyDn = new TextBox();
            this.textBox_fWeight = new TextBox();
            this.label24 = new Label();
            this.label23 = new Label();
            this.label22 = new Label();
            this.label21 = new Label();
            this.label20 = new Label();
            this.label18 = new Label();
            this.label17 = new Label();
            this.label16 = new Label();
            this.label15 = new Label();
            this.label14 = new Label();
            this.label13 = new Label();
            this.label12 = new Label();
            this.label10 = new Label();
            this.label9 = new Label();
            this.label6 = new Label();
            this.label5 = new Label();
            this.label4 = new Label();
            this.label7 = new Label();
            this.label8 = new Label();
            this.label19 = new Label();
            this.textBox_cMNo = new TextBox();
            this.textBox_cName = new TextBox();
            this.label25 = new Label();
            this.comboBox1 = new ComboBox();
            this.label26 = new Label();
            this.label33 = new Label();
            this.label34 = new Label();
            this.label35 = new Label();
            this.label39 = new Label();
            this.textBox1 = new TextBox();
            this.textBox2 = new TextBox();
            this.tlbMain.SuspendLayout();
            this.spliterMain.Panel1.SuspendLayout();
            this.spliterMain.Panel2.SuspendLayout();
            this.spliterMain.SuspendLayout();
            this.pnlListRecCount.SuspendLayout();
            ((ISupportInitialize) this.grdMatList).BeginInit();
            this.tbcMain.SuspendLayout();
            this.tbpMatInfo.SuspendLayout();
            this.tbp_ExProperty.SuspendLayout();
            this.pnlMatInfo.SuspendLayout();
            this.panel1.SuspendLayout();
            ((ISupportInitialize) this.dataGridView1).BeginInit();
            base.SuspendLayout();
            this.tlbMain.Items.AddRange(new ToolStripItem[] { 
                this.toolStripLabel1, this.toolStripSeparator2, this.toolStripSeparator1, this.tlb_M_New, this.tlb_M_Edit, this.toolStripSeparator3, this.tlb_M_Undo, this.tlb_M_Delete, this.toolStripSeparator4, this.tlb_M_Save, this.toolStripSeparator5, this.tlb_M_Refresh, this.tlb_M_Find, this.tlb_M_Print, this.toolStripSeparator6, this.toolStripSeparator7, 
                this.btn_M_Help, this.tlb_M_Exit, this.toolStripSeparator8, this.tlbSaveSysRts
             });
            this.tlbMain.Location = new Point(0, 0);
            this.tlbMain.Name = "tlbMain";
            this.tlbMain.Size = new Size(0x3b7, 0x19);
            this.tlbMain.TabIndex = 0x10;
            this.tlbMain.Text = "toolStrip1";
            this.toolStripLabel1.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.toolStripLabel1.ForeColor = SystemColors.ActiveCaption;
            this.toolStripLabel1.Name = "toolStripLabel1";
            this.toolStripLabel1.Size = new Size(0, 0x16);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new Size(6, 0x19);
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new Size(6, 0x19);
            this.tlb_M_New.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_New.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_New.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_New.Image = (Image) manager.GetObject("tlb_M_New.Image");
            this.tlb_M_New.ImageTransparentColor = Color.Magenta;
            this.tlb_M_New.Name = "tlb_M_New";
            this.tlb_M_New.Size = new Size(0x23, 0x16);
            this.tlb_M_New.Tag = "01";
            this.tlb_M_New.Text = "新建";
            this.tlb_M_Edit.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Edit.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Edit.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Edit.Image = (Image) manager.GetObject("tlb_M_Edit.Image");
            this.tlb_M_Edit.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Edit.Name = "tlb_M_Edit";
            this.tlb_M_Edit.Size = new Size(0x23, 0x16);
            this.tlb_M_Edit.Tag = "02";
            this.tlb_M_Edit.Text = "修改";
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new Size(6, 0x19);
            this.tlb_M_Undo.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Undo.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Undo.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Undo.Image = (Image) manager.GetObject("tlb_M_Undo.Image");
            this.tlb_M_Undo.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Undo.Name = "tlb_M_Undo";
            this.tlb_M_Undo.Size = new Size(0x23, 0x16);
            this.tlb_M_Undo.Tag = "03";
            this.tlb_M_Undo.Text = "取消";
            this.tlb_M_Delete.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Delete.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Delete.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Delete.Image = (Image) manager.GetObject("tlb_M_Delete.Image");
            this.tlb_M_Delete.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Delete.Name = "tlb_M_Delete";
            this.tlb_M_Delete.Size = new Size(0x23, 0x16);
            this.tlb_M_Delete.Tag = "04";
            this.tlb_M_Delete.Text = "删除";
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new Size(6, 0x19);
            this.tlb_M_Save.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Save.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Save.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Save.Image = (Image) manager.GetObject("tlb_M_Save.Image");
            this.tlb_M_Save.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Save.Name = "tlb_M_Save";
            this.tlb_M_Save.Size = new Size(0x23, 0x16);
            this.tlb_M_Save.Tag = "05";
            this.tlb_M_Save.Text = "保存";
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new Size(6, 0x19);
            this.tlb_M_Refresh.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Refresh.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Refresh.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Refresh.Image = (Image) manager.GetObject("tlb_M_Refresh.Image");
            this.tlb_M_Refresh.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Refresh.Name = "tlb_M_Refresh";
            this.tlb_M_Refresh.Size = new Size(0x23, 0x16);
            this.tlb_M_Refresh.Text = "刷新";
            this.tlb_M_Find.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Find.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Find.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Find.Image = (Image) manager.GetObject("tlb_M_Find.Image");
            this.tlb_M_Find.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Find.Name = "tlb_M_Find";
            this.tlb_M_Find.Size = new Size(0x23, 0x16);
            this.tlb_M_Find.Text = "查找";
            this.tlb_M_Find.Visible = false;
            this.tlb_M_Print.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Print.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Print.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Print.Image = (Image) manager.GetObject("tlb_M_Print.Image");
            this.tlb_M_Print.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Print.Name = "tlb_M_Print";
            this.tlb_M_Print.Size = new Size(0x23, 0x16);
            this.tlb_M_Print.Tag = "06";
            this.tlb_M_Print.Text = "打印";
            this.tlb_M_Print.Visible = false;
            this.toolStripSeparator6.Name = "toolStripSeparator6";
            this.toolStripSeparator6.Size = new Size(6, 0x19);
            this.toolStripSeparator7.Name = "toolStripSeparator7";
            this.toolStripSeparator7.Size = new Size(6, 0x19);
            this.btn_M_Help.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.btn_M_Help.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.btn_M_Help.ForeColor = SystemColors.ActiveCaption;
            this.btn_M_Help.Image = (Image) manager.GetObject("btn_M_Help.Image");
            this.btn_M_Help.ImageTransparentColor = Color.Magenta;
            this.btn_M_Help.Name = "btn_M_Help";
            this.btn_M_Help.Size = new Size(0x23, 0x16);
            this.btn_M_Help.Text = "帮助";
            this.btn_M_Help.Visible = false;
            this.tlb_M_Exit.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Exit.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Exit.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Exit.Image = (Image) manager.GetObject("tlb_M_Exit.Image");
            this.tlb_M_Exit.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Exit.Name = "tlb_M_Exit";
            this.tlb_M_Exit.Size = new Size(0x23, 0x16);
            this.tlb_M_Exit.Text = "退出";
            this.toolStripSeparator8.Name = "toolStripSeparator8";
            this.toolStripSeparator8.Size = new Size(6, 0x19);
            this.tlbSaveSysRts.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlbSaveSysRts.Image = (Image) manager.GetObject("tlbSaveSysRts.Image");
            this.tlbSaveSysRts.ImageTransparentColor = Color.Magenta;
            this.tlbSaveSysRts.Name = "tlbSaveSysRts";
            this.tlbSaveSysRts.Size = new Size(0x51, 0x16);
            this.tlbSaveSysRts.Text = "保存系统权限";
            this.tlbSaveSysRts.Visible = false;
            this.spliterMain.Dock = DockStyle.Fill;
            this.spliterMain.Location = new Point(0, 0x19);
            this.spliterMain.Name = "spliterMain";
            this.spliterMain.Panel1.Controls.Add(this.grdMatList);
            this.spliterMain.Panel1.Controls.Add(this.pnlListRecCount);
            this.spliterMain.Panel1.Controls.Add(this.grpCondition);
            this.spliterMain.Panel2.Controls.Add(this.tbcMain);
            this.spliterMain.Size = new Size(0x3b7, 0x203);
            this.spliterMain.SplitterDistance = 260;
            this.spliterMain.SplitterWidth = 8;
            this.spliterMain.TabIndex = 0x12;
            this.grpCondition.Dock = DockStyle.Top;
            this.grpCondition.Location = new Point(0, 0);
            this.grpCondition.Name = "grpCondition";
            this.grpCondition.Size = new Size(260, 100);
            this.grpCondition.TabIndex = 0;
            this.grpCondition.TabStop = false;
            this.grpCondition.Text = "过滤条件";
            this.pnlListRecCount.Controls.Add(this.lbl_M_Count);
            this.pnlListRecCount.Controls.Add(this.label1);
            this.pnlListRecCount.Dock = DockStyle.Bottom;
            this.pnlListRecCount.Location = new Point(0, 0x1e5);
            this.pnlListRecCount.Name = "pnlListRecCount";
            this.pnlListRecCount.Size = new Size(260, 30);
            this.pnlListRecCount.TabIndex = 1;
            this.grdMatList.AllowUserToAddRows = false;
            this.grdMatList.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.grdMatList.Columns.AddRange(new DataGridViewColumn[] { this.col_M_cMNo, this.col_M_cMName });
            this.grdMatList.Dock = DockStyle.Fill;
            this.grdMatList.Location = new Point(0, 100);
            this.grdMatList.Name = "grdMatList";
            this.grdMatList.RowHeadersVisible = false;
            this.grdMatList.RowTemplate.Height = 0x17;
            this.grdMatList.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.grdMatList.Size = new Size(260, 0x181);
            this.grdMatList.TabIndex = 2;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(9, 9);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x35, 12);
            this.label1.TabIndex = 0;
            this.label1.Text = "记录数：";
            this.lbl_M_Count.AutoSize = true;
            this.lbl_M_Count.Location = new Point(0x42, 9);
            this.lbl_M_Count.Name = "lbl_M_Count";
            this.lbl_M_Count.Size = new Size(11, 12);
            this.lbl_M_Count.TabIndex = 1;
            this.lbl_M_Count.Text = "0";
            this.tbcMain.Controls.Add(this.tbpMatInfo);
            this.tbcMain.Controls.Add(this.tbp_ExProperty);
            this.tbcMain.Dock = DockStyle.Fill;
            this.tbcMain.Location = new Point(0, 0);
            this.tbcMain.Name = "tbcMain";
            this.tbcMain.SelectedIndex = 0;
            this.tbcMain.Size = new Size(0x2ab, 0x203);
            this.tbcMain.TabIndex = 0;
            this.tbpMatInfo.Controls.Add(this.label55);
            this.tbpMatInfo.Controls.Add(this.cmb_nMatClass);
            this.tbpMatInfo.Controls.Add(this.label56);
            this.tbpMatInfo.Controls.Add(this.label48);
            this.tbpMatInfo.Controls.Add(this.cmb_cABC);
            this.tbpMatInfo.Controls.Add(this.label45);
            this.tbpMatInfo.Controls.Add(this.txt_cRemark);
            this.tbpMatInfo.Controls.Add(this.txt_cCSId);
            this.tbpMatInfo.Controls.Add(this.txt_nTag);
            this.tbpMatInfo.Controls.Add(this.label44);
            this.tbpMatInfo.Controls.Add(this.cmb_bIsAutoBatchNo);
            this.tbpMatInfo.Controls.Add(this.label11);
            this.tbpMatInfo.Controls.Add(this.btn_SelSupplier);
            this.tbpMatInfo.Controls.Add(this.label43);
            this.tbpMatInfo.Controls.Add(this.txt_cMatOther);
            this.tbpMatInfo.Controls.Add(this.label42);
            this.tbpMatInfo.Controls.Add(this.txt_cSupplier);
            this.tbpMatInfo.Controls.Add(this.txt_cMatQCLevel);
            this.tbpMatInfo.Controls.Add(this.label41);
            this.tbpMatInfo.Controls.Add(this.txt_cMatStyle);
            this.tbpMatInfo.Controls.Add(this.label40);
            this.tbpMatInfo.Controls.Add(this.label38);
            this.tbpMatInfo.Controls.Add(this.textBox_nAutoPromptDay);
            this.tbpMatInfo.Controls.Add(this.label37);
            this.tbpMatInfo.Controls.Add(this.cmb_bIsSubQtyForQC);
            this.tbpMatInfo.Controls.Add(this.label36);
            this.tbpMatInfo.Controls.Add(this.label31);
            this.tbpMatInfo.Controls.Add(this.label32);
            this.tbpMatInfo.Controls.Add(this.label29);
            this.tbpMatInfo.Controls.Add(this.label28);
            this.tbpMatInfo.Controls.Add(this.label27);
            this.tbpMatInfo.Controls.Add(this.label30);
            this.tbpMatInfo.Controls.Add(this.cmb_nPlaceMode);
            this.tbpMatInfo.Controls.Add(this.cmb_bIsQc);
            this.tbpMatInfo.Controls.Add(this.cmb_bIsFromErp);
            this.tbpMatInfo.Controls.Add(this.cmb_cTypeId2);
            this.tbpMatInfo.Controls.Add(this.cmb_cTypeId1);
            this.tbpMatInfo.Controls.Add(this.cmb_cUnit);
            this.tbpMatInfo.Controls.Add(this.cmb_cWHId);
            this.tbpMatInfo.Controls.Add(this.textBox_fDPSInQtyUp);
            this.tbpMatInfo.Controls.Add(this.textBox_cLinkId);
            this.tbpMatInfo.Controls.Add(this.textBox_cBorCode);
            this.tbpMatInfo.Controls.Add(this.textBox_cCreator);
            this.tbpMatInfo.Controls.Add(this.textBox1_cSpec);
            this.tbpMatInfo.Controls.Add(this.textBox_fSafeQtyDn);
            this.tbpMatInfo.Controls.Add(this.textBox_fSafeQtyUp);
            this.tbpMatInfo.Controls.Add(this.textBox_nKeepDay);
            this.tbpMatInfo.Controls.Add(this.textBox_fQtyBox);
            this.tbpMatInfo.Controls.Add(this.textBox_fDPSInQtyDn);
            this.tbpMatInfo.Controls.Add(this.textBox_fWeight);
            this.tbpMatInfo.Controls.Add(this.label24);
            this.tbpMatInfo.Controls.Add(this.label23);
            this.tbpMatInfo.Controls.Add(this.label22);
            this.tbpMatInfo.Controls.Add(this.label21);
            this.tbpMatInfo.Controls.Add(this.label20);
            this.tbpMatInfo.Controls.Add(this.label18);
            this.tbpMatInfo.Controls.Add(this.label17);
            this.tbpMatInfo.Controls.Add(this.label16);
            this.tbpMatInfo.Controls.Add(this.label15);
            this.tbpMatInfo.Controls.Add(this.label14);
            this.tbpMatInfo.Controls.Add(this.label13);
            this.tbpMatInfo.Controls.Add(this.label12);
            this.tbpMatInfo.Controls.Add(this.label10);
            this.tbpMatInfo.Controls.Add(this.label9);
            this.tbpMatInfo.Controls.Add(this.label6);
            this.tbpMatInfo.Controls.Add(this.label5);
            this.tbpMatInfo.Controls.Add(this.label4);
            this.tbpMatInfo.Controls.Add(this.label7);
            this.tbpMatInfo.Controls.Add(this.label8);
            this.tbpMatInfo.Controls.Add(this.label19);
            this.tbpMatInfo.Controls.Add(this.textBox_cMNo);
            this.tbpMatInfo.Controls.Add(this.textBox_cName);
            this.tbpMatInfo.Location = new Point(4, 0x15);
            this.tbpMatInfo.Name = "tbpMatInfo";
            this.tbpMatInfo.Padding = new Padding(3);
            this.tbpMatInfo.Size = new Size(0x2a3, 490);
            this.tbpMatInfo.TabIndex = 0;
            this.tbpMatInfo.Text = "物料组信息";
            this.tbpMatInfo.UseVisualStyleBackColor = true;
            this.tbp_ExProperty.Controls.Add(this.dataGridView1);
            this.tbp_ExProperty.Controls.Add(this.panel1);
            this.tbp_ExProperty.Controls.Add(this.pnlMatInfo);
            this.tbp_ExProperty.Location = new Point(4, 0x15);
            this.tbp_ExProperty.Name = "tbp_ExProperty";
            this.tbp_ExProperty.Padding = new Padding(3);
            this.tbp_ExProperty.Size = new Size(0x2a3, 490);
            this.tbp_ExProperty.TabIndex = 1;
            this.tbp_ExProperty.Text = "物料辅助属性列表";
            this.tbp_ExProperty.UseVisualStyleBackColor = true;
            this.col_M_cMNo.HeaderText = "物料编号";
            this.col_M_cMNo.Name = "col_M_cMNo";
            this.col_M_cMName.HeaderText = "物料名称";
            this.col_M_cMName.Name = "col_M_cMName";
            this.col_M_cMName.Width = 150;
            this.pnlMatInfo.Controls.Add(this.label25);
            this.pnlMatInfo.Controls.Add(this.comboBox1);
            this.pnlMatInfo.Controls.Add(this.label26);
            this.pnlMatInfo.Controls.Add(this.label33);
            this.pnlMatInfo.Controls.Add(this.label34);
            this.pnlMatInfo.Controls.Add(this.label35);
            this.pnlMatInfo.Controls.Add(this.label39);
            this.pnlMatInfo.Controls.Add(this.textBox1);
            this.pnlMatInfo.Controls.Add(this.textBox2);
            this.pnlMatInfo.Dock = DockStyle.Top;
            this.pnlMatInfo.Location = new Point(3, 3);
            this.pnlMatInfo.Name = "pnlMatInfo";
            this.pnlMatInfo.Size = new Size(0x29d, 0x53);
            this.pnlMatInfo.TabIndex = 1;
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.label3);
            this.panel1.Dock = DockStyle.Bottom;
            this.panel1.Location = new Point(3, 0x1c9);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(0x29d, 30);
            this.panel1.TabIndex = 3;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(0x42, 9);
            this.label2.Name = "label2";
            this.label2.Size = new Size(11, 12);
            this.label2.TabIndex = 1;
            this.label2.Text = "0";
            this.label3.AutoSize = true;
            this.label3.Location = new Point(9, 9);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x35, 12);
            this.label3.TabIndex = 0;
            this.label3.Text = "记录数：";
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dataGridView1.Columns.AddRange(new DataGridViewColumn[] { this.dataGridViewTextBoxColumn1, this.dataGridViewTextBoxColumn2 });
            this.dataGridView1.Dock = DockStyle.Fill;
            this.dataGridView1.Location = new Point(3, 0x56);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersVisible = false;
            this.dataGridView1.RowTemplate.Height = 0x17;
            this.dataGridView1.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dataGridView1.Size = new Size(0x29d, 0x173);
            this.dataGridView1.TabIndex = 4;
            this.dataGridViewTextBoxColumn1.HeaderText = "物料编号";
            this.dataGridViewTextBoxColumn1.Name = "dataGridViewTextBoxColumn1";
            this.dataGridViewTextBoxColumn2.HeaderText = "物料名称";
            this.dataGridViewTextBoxColumn2.Name = "dataGridViewTextBoxColumn2";
            this.dataGridViewTextBoxColumn2.Width = 150;
            this.label55.AutoSize = true;
            this.label55.ForeColor = SystemColors.ActiveCaption;
            this.label55.Location = new Point(0x288, 0x13);
            this.label55.Name = "label55";
            this.label55.Size = new Size(11, 12);
            this.label55.TabIndex = 260;
            this.label55.Text = "*";
            this.cmb_nMatClass.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_nMatClass.FormattingEnabled = true;
            this.cmb_nMatClass.Location = new Point(0x1b2, 12);
            this.cmb_nMatClass.Name = "cmb_nMatClass";
            this.cmb_nMatClass.Size = new Size(0xcf, 20);
            this.cmb_nMatClass.TabIndex = 0xbd;
            this.cmb_nMatClass.Tag = "101";
            this.label56.AutoSize = true;
            this.label56.Location = new Point(0x164, 0x11);
            this.label56.Name = "label56";
            this.label56.Size = new Size(0x35, 12);
            this.label56.TabIndex = 0x103;
            this.label56.Text = "物料类型";
            this.label48.AutoSize = true;
            this.label48.Location = new Point(0x1d7, 180);
            this.label48.Name = "label48";
            this.label48.Size = new Size(0x2f, 12);
            this.label48.TabIndex = 0x102;
            this.label48.Text = "ABC属性";
            this.cmb_cABC.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_cABC.FormattingEnabled = true;
            this.cmb_cABC.Items.AddRange(new object[] { "A", "B", "C" });
            this.cmb_cABC.Location = new Point(0x209, 0xb1);
            this.cmb_cABC.Name = "cmb_cABC";
            this.cmb_cABC.Size = new Size(0x79, 20);
            this.cmb_cABC.TabIndex = 0x101;
            this.cmb_cABC.Tag = "1";
            this.label45.AutoSize = true;
            this.label45.Location = new Point(15, 0xcc);
            this.label45.Name = "label45";
            this.label45.Size = new Size(0x1d, 12);
            this.label45.TabIndex = 0x100;
            this.label45.Text = "备注";
            this.txt_cRemark.Location = new Point(0x63, 0xc9);
            this.txt_cRemark.Name = "txt_cRemark";
            this.txt_cRemark.Size = new Size(0x21e, 0x15);
            this.txt_cRemark.TabIndex = 0xff;
            this.txt_cRemark.Tag = "0";
            this.txt_cCSId.Enabled = false;
            this.txt_cCSId.Location = new Point(0x63, 0x99);
            this.txt_cCSId.Name = "txt_cCSId";
            this.txt_cCSId.Size = new Size(150, 0x15);
            this.txt_cCSId.TabIndex = 0xfe;
            this.txt_cCSId.Tag = "0";
            this.txt_nTag.Location = new Point(0x19d, 0x176);
            this.txt_nTag.Name = "txt_nTag";
            this.txt_nTag.Size = new Size(0x2d, 0x15);
            this.txt_nTag.TabIndex = 0xd8;
            this.txt_nTag.Tag = "0";
            this.txt_nTag.Text = "0";
            this.label44.AutoSize = true;
            this.label44.Location = new Point(0x167, 0x176);
            this.label44.Name = "label44";
            this.label44.Size = new Size(0x35, 12);
            this.label44.TabIndex = 0xfd;
            this.label44.Text = "自增批次";
            this.cmb_bIsAutoBatchNo.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_bIsAutoBatchNo.FormattingEnabled = true;
            this.cmb_bIsAutoBatchNo.Items.AddRange(new object[] { "否", "是" });
            this.cmb_bIsAutoBatchNo.Location = new Point(0x141, 0x176);
            this.cmb_bIsAutoBatchNo.Name = "cmb_bIsAutoBatchNo";
            this.cmb_bIsAutoBatchNo.Size = new Size(0x24, 20);
            this.cmb_bIsAutoBatchNo.TabIndex = 0xd7;
            this.cmb_bIsAutoBatchNo.Tag = "102";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(220, 0x176);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x65, 12);
            this.label11.TabIndex = 0xfc;
            this.label11.Text = "是否自动递增批号";
            this.btn_SelSupplier.Location = new Point(0x26a, 0x98);
            this.btn_SelSupplier.Name = "btn_SelSupplier";
            this.btn_SelSupplier.Size = new Size(0x18, 0x17);
            this.btn_SelSupplier.TabIndex = 0xfb;
            this.btn_SelSupplier.Text = "…";
            this.btn_SelSupplier.UseVisualStyleBackColor = true;
            this.label43.AutoSize = true;
            this.label43.Location = new Point(15, 180);
            this.label43.Name = "label43";
            this.label43.Size = new Size(0x35, 12);
            this.label43.TabIndex = 250;
            this.label43.Text = "其他属性";
            this.txt_cMatOther.Location = new Point(0x63, 0xb1);
            this.txt_cMatOther.Name = "txt_cMatOther";
            this.txt_cMatOther.Size = new Size(0x174, 0x15);
            this.txt_cMatOther.TabIndex = 0xc9;
            this.txt_cMatOther.Tag = "0";
            this.label42.AutoSize = true;
            this.label42.Location = new Point(15, 0x9d);
            this.label42.Name = "label42";
            this.label42.Size = new Size(0x53, 12);
            this.label42.TabIndex = 0xf9;
            this.label42.Text = "供应商/生产商";
            this.txt_cSupplier.Enabled = false;
            this.txt_cSupplier.Location = new Point(0xff, 0x99);
            this.txt_cSupplier.Name = "txt_cSupplier";
            this.txt_cSupplier.Size = new Size(0x165, 0x15);
            this.txt_cSupplier.TabIndex = 200;
            this.txt_cSupplier.Tag = "0";
            this.txt_cMatQCLevel.Location = new Point(0x1b2, 0x81);
            this.txt_cMatQCLevel.Name = "txt_cMatQCLevel";
            this.txt_cMatQCLevel.Size = new Size(0xd0, 0x15);
            this.txt_cMatQCLevel.TabIndex = 0xc7;
            this.txt_cMatQCLevel.Tag = "0";
            this.label41.AutoSize = true;
            this.label41.Location = new Point(0x164, 0x81);
            this.label41.Name = "label41";
            this.label41.Size = new Size(0x35, 12);
            this.label41.TabIndex = 0xf8;
            this.label41.Text = "质量等级";
            this.txt_cMatStyle.Location = new Point(0x63, 0x81);
            this.txt_cMatStyle.Name = "txt_cMatStyle";
            this.txt_cMatStyle.Size = new Size(0xd8, 0x15);
            this.txt_cMatStyle.TabIndex = 0xc6;
            this.txt_cMatStyle.Tag = "0";
            this.label40.AutoSize = true;
            this.label40.Location = new Point(0x10, 0x81);
            this.label40.Name = "label40";
            this.label40.Size = new Size(0x2f, 12);
            this.label40.TabIndex = 0xf7;
            this.label40.Text = "款   式";
            this.label38.AutoSize = true;
            this.label38.Location = new Point(0x250, 0x160);
            this.label38.Name = "label38";
            this.label38.Size = new Size(0x11, 12);
            this.label38.TabIndex = 0xf6;
            this.label38.Text = "天";
            this.textBox_nAutoPromptDay.Location = new Point(0x1f7, 350);
            this.textBox_nAutoPromptDay.Name = "textBox_nAutoPromptDay";
            this.textBox_nAutoPromptDay.Size = new Size(0x55, 0x15);
            this.textBox_nAutoPromptDay.TabIndex = 0xd5;
            this.textBox_nAutoPromptDay.Tag = "0";
            this.textBox_nAutoPromptDay.Text = "10";
            this.label37.AutoSize = true;
            this.label37.Location = new Point(0x182, 350);
            this.label37.Name = "label37";
            this.label37.Size = new Size(0x71, 12);
            this.label37.TabIndex = 0xf5;
            this.label37.Text = "有效期自动提醒天数";
            this.cmb_bIsSubQtyForQC.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_bIsSubQtyForQC.FormattingEnabled = true;
            this.cmb_bIsSubQtyForQC.Items.AddRange(new object[] { "否", "是" });
            this.cmb_bIsSubQtyForQC.Location = new Point(0x20d, 0x147);
            this.cmb_bIsSubQtyForQC.Name = "cmb_bIsSubQtyForQC";
            this.cmb_bIsSubQtyForQC.Size = new Size(0x52, 20);
            this.cmb_bIsSubQtyForQC.TabIndex = 0xd3;
            this.cmb_bIsSubQtyForQC.Tag = "102";
            this.label36.AutoSize = true;
            this.label36.Location = new Point(0x182, 0x147);
            this.label36.Name = "label36";
            this.label36.Size = new Size(0x89, 12);
            this.label36.TabIndex = 0xf4;
            this.label36.Text = "质检取样时是否扣减数量";
            this.label31.AutoSize = true;
            this.label31.ForeColor = SystemColors.ActiveCaption;
            this.label31.Location = new Point(0x13f, 0x3e);
            this.label31.Name = "label31";
            this.label31.Size = new Size(11, 12);
            this.label31.TabIndex = 0xf3;
            this.label31.Text = "*";
            this.label32.AutoSize = true;
            this.label32.ForeColor = SystemColors.ActiveCaption;
            this.label32.Location = new Point(0x13f, 0x54);
            this.label32.Name = "label32";
            this.label32.Size = new Size(11, 12);
            this.label32.TabIndex = 0xf2;
            this.label32.Text = "*";
            this.label29.AutoSize = true;
            this.label29.ForeColor = SystemColors.ActiveCaption;
            this.label29.Location = new Point(0x288, 0x3f);
            this.label29.Name = "label29";
            this.label29.Size = new Size(11, 12);
            this.label29.TabIndex = 0xf1;
            this.label29.Text = "*";
            this.label28.AutoSize = true;
            this.label28.ForeColor = SystemColors.ActiveCaption;
            this.label28.Location = new Point(0x288, 0x56);
            this.label28.Name = "label28";
            this.label28.Size = new Size(11, 12);
            this.label28.TabIndex = 240;
            this.label28.Text = "*";
            this.label27.AutoSize = true;
            this.label27.ForeColor = SystemColors.ActiveCaption;
            this.label27.Location = new Point(0x288, 0x2a);
            this.label27.Name = "label27";
            this.label27.Size = new Size(11, 12);
            this.label27.TabIndex = 0xef;
            this.label27.Text = "*";
            this.label30.AutoSize = true;
            this.label30.ForeColor = SystemColors.ActiveCaption;
            this.label30.Location = new Point(0xf3, 20);
            this.label30.Name = "label30";
            this.label30.Size = new Size(11, 12);
            this.label30.TabIndex = 0xee;
            this.label30.Text = "*";
            this.cmb_nPlaceMode.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_nPlaceMode.FormattingEnabled = true;
            this.cmb_nPlaceMode.Items.AddRange(new object[] { "托盘", "周转箱" });
            this.cmb_nPlaceMode.Location = new Point(0xab, 0xe5);
            this.cmb_nPlaceMode.Name = "cmb_nPlaceMode";
            this.cmb_nPlaceMode.Size = new Size(0x97, 20);
            this.cmb_nPlaceMode.TabIndex = 0xca;
            this.cmb_nPlaceMode.Tag = "102";
            this.cmb_bIsQc.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_bIsQc.FormattingEnabled = true;
            this.cmb_bIsQc.Items.AddRange(new object[] { "否", "是" });
            this.cmb_bIsQc.Location = new Point(170, 0x145);
            this.cmb_bIsQc.Name = "cmb_bIsQc";
            this.cmb_bIsQc.Size = new Size(0x98, 20);
            this.cmb_bIsQc.TabIndex = 210;
            this.cmb_bIsQc.Tag = "102";
            this.cmb_bIsFromErp.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_bIsFromErp.FormattingEnabled = true;
            this.cmb_bIsFromErp.Items.AddRange(new object[] { "否", "是" });
            this.cmb_bIsFromErp.Location = new Point(170, 0x173);
            this.cmb_bIsFromErp.Name = "cmb_bIsFromErp";
            this.cmb_bIsFromErp.Size = new Size(0x2c, 20);
            this.cmb_bIsFromErp.TabIndex = 0xd6;
            this.cmb_bIsFromErp.Tag = "102";
            this.cmb_cTypeId2.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_cTypeId2.FormattingEnabled = true;
            this.cmb_cTypeId2.Location = new Point(0x63, 0x54);
            this.cmb_cTypeId2.Name = "cmb_cTypeId2";
            this.cmb_cTypeId2.Size = new Size(0xd8, 20);
            this.cmb_cTypeId2.TabIndex = 0xc2;
            this.cmb_cTypeId2.Tag = "101";
            this.cmb_cTypeId1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cmb_cTypeId1.FormattingEnabled = true;
            this.cmb_cTypeId1.Location = new Point(0x1b2, 0x54);
            this.cmb_cTypeId1.Name = "cmb_cTypeId1";
            this.cmb_cTypeId1.Size = new Size(0xcf, 20);
            this.cmb_cTypeId1.TabIndex = 0xc3;
            this.cmb_cTypeId1.Tag = "101";
            this.cmb_cUnit.FormattingEnabled = true;
            this.cmb_cUnit.Location = new Point(0x63, 0x3e);
            this.cmb_cUnit.Name = "cmb_cUnit";
            this.cmb_cUnit.Size = new Size(0xd9, 20);
            this.cmb_cUnit.TabIndex = 0xc0;
            this.cmb_cUnit.Tag = "101";
            this.cmb_cUnit.Text = "Bind SelectedValue";
            this.cmb_cWHId.FormattingEnabled = true;
            this.cmb_cWHId.Location = new Point(0x63, 0x6a);
            this.cmb_cWHId.Name = "cmb_cWHId";
            this.cmb_cWHId.Size = new Size(0xd8, 20);
            this.cmb_cWHId.TabIndex = 0xc4;
            this.cmb_cWHId.Tag = "101";
            this.cmb_cWHId.Text = "Bind SelectedValue";
            this.textBox_fDPSInQtyUp.Location = new Point(0x1c4, 0xfd);
            this.textBox_fDPSInQtyUp.Name = "textBox_fDPSInQtyUp";
            this.textBox_fDPSInQtyUp.Size = new Size(0x9b, 0x15);
            this.textBox_fDPSInQtyUp.TabIndex = 0xcd;
            this.textBox_fDPSInQtyUp.Tag = "0";
            this.textBox_cLinkId.Location = new Point(0x1c4, 0xe5);
            this.textBox_cLinkId.Name = "textBox_cLinkId";
            this.textBox_cLinkId.Size = new Size(0x9b, 0x15);
            this.textBox_cLinkId.TabIndex = 0xcb;
            this.textBox_cLinkId.Tag = "0";
            this.textBox_cBorCode.Location = new Point(0x1c4, 0x115);
            this.textBox_cBorCode.Name = "textBox_cBorCode";
            this.textBox_cBorCode.Size = new Size(0x9b, 0x15);
            this.textBox_cBorCode.TabIndex = 0xd0;
            this.textBox_cBorCode.Tag = "0";
            this.textBox_cCreator.Location = new Point(0x206, 0x177);
            this.textBox_cCreator.Name = "textBox_cCreator";
            this.textBox_cCreator.Size = new Size(0x59, 0x15);
            this.textBox_cCreator.TabIndex = 0xd9;
            this.textBox_cCreator.Tag = "0";
            this.textBox1_cSpec.Location = new Point(0x1b2, 0x6a);
            this.textBox1_cSpec.Name = "textBox1_cSpec";
            this.textBox1_cSpec.Size = new Size(0xd0, 0x15);
            this.textBox1_cSpec.TabIndex = 0xc5;
            this.textBox1_cSpec.Tag = "0";
            this.textBox_fSafeQtyDn.Location = new Point(0xab, 0x12d);
            this.textBox_fSafeQtyDn.Name = "textBox_fSafeQtyDn";
            this.textBox_fSafeQtyDn.Size = new Size(0x97, 0x15);
            this.textBox_fSafeQtyDn.TabIndex = 0xcf;
            this.textBox_fSafeQtyDn.Tag = "0";
            this.textBox_fSafeQtyUp.Location = new Point(0x1c4, 0x12d);
            this.textBox_fSafeQtyUp.Name = "textBox_fSafeQtyUp";
            this.textBox_fSafeQtyUp.Size = new Size(0x9b, 0x15);
            this.textBox_fSafeQtyUp.TabIndex = 0xd1;
            this.textBox_fSafeQtyUp.Tag = "0";
            this.textBox_nKeepDay.Location = new Point(170, 0x15c);
            this.textBox_nKeepDay.Name = "textBox_nKeepDay";
            this.textBox_nKeepDay.Size = new Size(0x99, 0x15);
            this.textBox_nKeepDay.TabIndex = 0xd4;
            this.textBox_nKeepDay.Tag = "0";
            this.textBox_fQtyBox.Location = new Point(0x1b2, 0x3e);
            this.textBox_fQtyBox.Name = "textBox_fQtyBox";
            this.textBox_fQtyBox.Size = new Size(0xd0, 0x15);
            this.textBox_fQtyBox.TabIndex = 0xc1;
            this.textBox_fQtyBox.Tag = "0";
            this.textBox_fQtyBox.Text = "0";
            this.textBox_fDPSInQtyDn.Location = new Point(0xab, 0xfd);
            this.textBox_fDPSInQtyDn.Name = "textBox_fDPSInQtyDn";
            this.textBox_fDPSInQtyDn.Size = new Size(0x97, 0x15);
            this.textBox_fDPSInQtyDn.TabIndex = 0xcc;
            this.textBox_fDPSInQtyDn.Tag = "0";
            this.textBox_fWeight.Location = new Point(0xab, 0x115);
            this.textBox_fWeight.Name = "textBox_fWeight";
            this.textBox_fWeight.Size = new Size(0x97, 0x15);
            this.textBox_fWeight.TabIndex = 0xce;
            this.textBox_fWeight.Tag = "0";
            this.label24.AutoSize = true;
            this.label24.Location = new Point(0x164, 0x3e);
            this.label24.Name = "label24";
            this.label24.Size = new Size(0x47, 12);
            this.label24.TabIndex = 0xed;
            this.label24.Text = "满盘/箱数量";
            this.label23.AutoSize = true;
            this.label23.Location = new Point(0x61, 0xfd);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x35, 12);
            this.label23.TabIndex = 0xec;
            this.label23.Text = "最小补货";
            this.label22.AutoSize = true;
            this.label22.Location = new Point(0x182, 0xfd);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x35, 12);
            this.label22.TabIndex = 0xeb;
            this.label22.Text = "最大补货";
            this.label21.AutoSize = true;
            this.label21.Location = new Point(0x61, 0xe5);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x35, 12);
            this.label21.TabIndex = 0xea;
            this.label21.Text = "存货模式";
            this.label20.AutoSize = true;
            this.label20.Location = new Point(0x182, 0xe5);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x35, 12);
            this.label20.TabIndex = 0xe9;
            this.label20.Text = "关联编码";
            this.label18.AutoSize = true;
            this.label18.Location = new Point(0x61, 0x145);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x29, 12);
            this.label18.TabIndex = 0xe8;
            this.label18.Text = "是否QC";
            this.label17.AutoSize = true;
            this.label17.Location = new Point(0x182, 0x115);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x35, 12);
            this.label17.TabIndex = 0xe7;
            this.label17.Text = "条形编码";
            this.label16.AutoSize = true;
            this.label16.Location = new Point(0x164, 0x54);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x35, 12);
            this.label16.TabIndex = 230;
            this.label16.Text = "物料分类";
            this.label15.AutoSize = true;
            this.label15.Location = new Point(0x61, 0x12d);
            this.label15.Name = "label15";
            this.label15.Size = new Size(0x35, 12);
            this.label15.TabIndex = 0xe5;
            this.label15.Text = "最小库存";
            this.label14.AutoSize = true;
            this.label14.Location = new Point(0x182, 0x12d);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x35, 12);
            this.label14.TabIndex = 0xe4;
            this.label14.Text = "最大库存";
            this.label13.AutoSize = true;
            this.label13.Location = new Point(0x61, 0x15c);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0x35, 12);
            this.label13.TabIndex = 0xe3;
            this.label13.Text = "质保天数";
            this.label12.AutoSize = true;
            this.label12.Location = new Point(0x61, 0x173);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x47, 12);
            this.label12.TabIndex = 0xe2;
            this.label12.Text = "是否来源ERP";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(0x1ce, 0x178);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x35, 12);
            this.label10.TabIndex = 0xe1;
            this.label10.Text = "操作人员";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(0x10, 0x6a);
            this.label9.Name = "label9";
            this.label9.Size = new Size(0x35, 12);
            this.label9.TabIndex = 0xe0;
            this.label9.Text = "默认仓库";
            this.label6.AutoSize = true;
            this.label6.Location = new Point(0x10, 0x54);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x35, 12);
            this.label6.TabIndex = 0xdf;
            this.label6.Text = "会计分类";
            this.label5.AutoSize = true;
            this.label5.Location = new Point(0x61, 0x115);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x35, 12);
            this.label5.TabIndex = 0xde;
            this.label5.Text = "单位重量";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(0x10, 0x3e);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x35, 12);
            this.label4.TabIndex = 0xdd;
            this.label4.Text = "物料单位";
            this.label7.AutoSize = true;
            this.label7.Location = new Point(0x164, 0x6a);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x35, 12);
            this.label7.TabIndex = 220;
            this.label7.Text = "规格型号";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(15, 0x2a);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x35, 12);
            this.label8.TabIndex = 0xdb;
            this.label8.Text = "物料名称";
            this.label19.AutoSize = true;
            this.label19.Location = new Point(15, 0x13);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x35, 12);
            this.label19.TabIndex = 0xda;
            this.label19.Text = "物料编码";
            this.textBox_cMNo.Location = new Point(0x63, 0x10);
            this.textBox_cMNo.Name = "textBox_cMNo";
            this.textBox_cMNo.ReadOnly = true;
            this.textBox_cMNo.Size = new Size(140, 0x15);
            this.textBox_cMNo.TabIndex = 190;
            this.textBox_cMNo.Tag = "0";
            this.textBox_cName.Location = new Point(0x63, 0x27);
            this.textBox_cName.Name = "textBox_cName";
            this.textBox_cName.Size = new Size(0x21f, 0x15);
            this.textBox_cName.TabIndex = 0xbf;
            this.textBox_cName.Tag = "0";
            this.label25.AutoSize = true;
            this.label25.ForeColor = SystemColors.ActiveCaption;
            this.label25.Location = new Point(0x289, 0x17);
            this.label25.Name = "label25";
            this.label25.Size = new Size(11, 12);
            this.label25.TabIndex = 0x10d;
            this.label25.Text = "*";
            this.comboBox1.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Location = new Point(0x1b3, 0x10);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(0xcf, 20);
            this.comboBox1.TabIndex = 0x105;
            this.comboBox1.Tag = "101";
            this.label26.AutoSize = true;
            this.label26.Location = new Point(0x165, 0x15);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x35, 12);
            this.label26.TabIndex = 0x10c;
            this.label26.Text = "物料类型";
            this.label33.AutoSize = true;
            this.label33.ForeColor = SystemColors.ActiveCaption;
            this.label33.Location = new Point(0x289, 0x2e);
            this.label33.Name = "label33";
            this.label33.Size = new Size(11, 12);
            this.label33.TabIndex = 0x10b;
            this.label33.Text = "*";
            this.label34.AutoSize = true;
            this.label34.ForeColor = SystemColors.ActiveCaption;
            this.label34.Location = new Point(0xf4, 0x18);
            this.label34.Name = "label34";
            this.label34.Size = new Size(11, 12);
            this.label34.TabIndex = 0x10a;
            this.label34.Text = "*";
            this.label35.AutoSize = true;
            this.label35.Location = new Point(0x10, 0x2e);
            this.label35.Name = "label35";
            this.label35.Size = new Size(0x35, 12);
            this.label35.TabIndex = 0x109;
            this.label35.Text = "物料名称";
            this.label39.AutoSize = true;
            this.label39.Location = new Point(0x10, 0x17);
            this.label39.Name = "label39";
            this.label39.Size = new Size(0x35, 12);
            this.label39.TabIndex = 0x108;
            this.label39.Text = "物料编码";
            this.textBox1.Location = new Point(100, 20);
            this.textBox1.Name = "textBox1";
            this.textBox1.ReadOnly = true;
            this.textBox1.Size = new Size(140, 0x15);
            this.textBox1.TabIndex = 0x106;
            this.textBox1.Tag = "0";
            this.textBox2.Location = new Point(100, 0x2b);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(0x21f, 0x15);
            this.textBox2.TabIndex = 0x107;
            this.textBox2.Tag = "0";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(0x3b7, 540);
            base.Controls.Add(this.spliterMain);
            base.Controls.Add(this.tlbMain);
            base.Name = "frmMatMappingList";
            this.Text = "物料辅助属性对应表";
            base.Load += new EventHandler(this.frmMatMappingList_Load);
            this.tlbMain.ResumeLayout(false);
            this.tlbMain.PerformLayout();
            this.spliterMain.Panel1.ResumeLayout(false);
            this.spliterMain.Panel2.ResumeLayout(false);
            this.spliterMain.ResumeLayout(false);
            this.pnlListRecCount.ResumeLayout(false);
            this.pnlListRecCount.PerformLayout();
            ((ISupportInitialize) this.grdMatList).EndInit();
            this.tbcMain.ResumeLayout(false);
            this.tbpMatInfo.ResumeLayout(false);
            this.tbpMatInfo.PerformLayout();
            this.tbp_ExProperty.ResumeLayout(false);
            this.pnlMatInfo.ResumeLayout(false);
            this.pnlMatInfo.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((ISupportInitialize) this.dataGridView1).EndInit();
            base.ResumeLayout(false);
            base.PerformLayout();
        }
    }
}

