namespace WarehouseBase
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;
    using UI;

    public class frmWCarRows : FrmSTable
    {
        private ToolStripButton btn_M_Help;
        private ComboBox cmb_cWHId;
        private DataGridViewTextBoxColumn colcArea;
        private DataGridViewTextBoxColumn colcPltSpec;
        private DataGridViewTextBoxColumn colcWHId;
        private IContainer components = null;
        public DataGridView grdList;
        private Label label1;
        private Label label3;
        private Label label6;
        private Panel pnlEdit;
        public ToolStripButton tlb_M_Check;
        public ToolStripButton tlb_M_Delete;
        public ToolStripButton tlb_M_Edit;
        private ToolStripButton tlb_M_Exit;
        public ToolStripButton tlb_M_Find;
        public ToolStripButton tlb_M_New;
        public ToolStripButton tlb_M_Print;
        public ToolStripButton tlb_M_Refresh;
        public ToolStripButton tlb_M_Save;
        private ToolStripButton tlb_M_UnCheck;
        public ToolStripButton tlb_M_Undo;
        public ToolStrip tlbMain;
        public ToolStripLabel toolStripLabel1;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripSeparator toolStripSeparator3;
        private ToolStripSeparator toolStripSeparator4;
        private ToolStripSeparator toolStripSeparator5;
        private ToolStripSeparator toolStripSeparator6;
        private ToolStripSeparator toolStripSeparator7;
        private ToolStripSeparator toolStripSeparator8;
        private TextBox txt_cCarNo;
        private TextBox txt_nRow;

        public frmWCarRows()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            ComponentResourceManager manager = new ComponentResourceManager(typeof(frmWCarRows));
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            this.cmb_cWHId = new ComboBox();
            this.tlb_M_Exit = new ToolStripButton();
            this.toolStripSeparator8 = new ToolStripSeparator();
            this.label3 = new Label();
            this.tlb_M_UnCheck = new ToolStripButton();
            this.tlb_M_Check = new ToolStripButton();
            this.btn_M_Help = new ToolStripButton();
            this.toolStripSeparator7 = new ToolStripSeparator();
            this.colcWHId = new DataGridViewTextBoxColumn();
            this.grdList = new DataGridView();
            this.colcPltSpec = new DataGridViewTextBoxColumn();
            this.colcArea = new DataGridViewTextBoxColumn();
            this.tlb_M_New = new ToolStripButton();
            this.toolStripSeparator1 = new ToolStripSeparator();
            this.toolStripSeparator3 = new ToolStripSeparator();
            this.tlb_M_Edit = new ToolStripButton();
            this.pnlEdit = new Panel();
            this.tlbMain = new ToolStrip();
            this.toolStripLabel1 = new ToolStripLabel();
            this.toolStripSeparator2 = new ToolStripSeparator();
            this.tlb_M_Undo = new ToolStripButton();
            this.tlb_M_Delete = new ToolStripButton();
            this.toolStripSeparator4 = new ToolStripSeparator();
            this.tlb_M_Save = new ToolStripButton();
            this.toolStripSeparator5 = new ToolStripSeparator();
            this.tlb_M_Refresh = new ToolStripButton();
            this.tlb_M_Find = new ToolStripButton();
            this.tlb_M_Print = new ToolStripButton();
            this.toolStripSeparator6 = new ToolStripSeparator();
            this.label6 = new Label();
            this.txt_cCarNo = new TextBox();
            this.label1 = new Label();
            this.txt_nRow = new TextBox();
            ((ISupportInitialize) this.grdList).BeginInit();
            this.pnlEdit.SuspendLayout();
            this.tlbMain.SuspendLayout();
            base.SuspendLayout();
            this.cmb_cWHId.FormattingEnabled = true;
            this.cmb_cWHId.Location = new Point(0x6d, 0x27);
            this.cmb_cWHId.Name = "cmb_cWHId";
            this.cmb_cWHId.Size = new Size(0xb3, 20);
            this.cmb_cWHId.TabIndex = 14;
            this.cmb_cWHId.Tag = "101";
            this.cmb_cWHId.Text = "Bind SelectedValue";
            this.tlb_M_Exit.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Exit.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Exit.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Exit.Image = (Image) manager.GetObject("tlb_M_Exit.Image");
            this.tlb_M_Exit.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Exit.Name = "tlb_M_Exit";
            this.tlb_M_Exit.Size = new Size(0x23, 0x16);
            this.tlb_M_Exit.Text = "退出";
            this.toolStripSeparator8.Name = "toolStripSeparator8";
            this.toolStripSeparator8.Size = new Size(6, 0x19);
            this.label3.AutoSize = true;
            this.label3.Location = new Point(0x19, 0x2f);
            this.label3.Name = "label3";
            this.label3.Size = new Size(0x29, 12);
            this.label3.TabIndex = 13;
            this.label3.Text = "仓库：";
            this.tlb_M_UnCheck.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_UnCheck.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_UnCheck.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_UnCheck.Image = (Image) manager.GetObject("tlb_M_UnCheck.Image");
            this.tlb_M_UnCheck.ImageTransparentColor = Color.Magenta;
            this.tlb_M_UnCheck.Name = "tlb_M_UnCheck";
            this.tlb_M_UnCheck.Size = new Size(0x3d, 0x16);
            this.tlb_M_UnCheck.Tag = "08";
            this.tlb_M_UnCheck.Text = "取消审核";
            this.tlb_M_UnCheck.Visible = false;
            this.tlb_M_Check.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Check.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Check.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Check.Image = (Image) manager.GetObject("tlb_M_Check.Image");
            this.tlb_M_Check.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Check.Name = "tlb_M_Check";
            this.tlb_M_Check.Size = new Size(0x23, 0x16);
            this.tlb_M_Check.Tag = "7";
            this.tlb_M_Check.Text = "审核";
            this.tlb_M_Check.Visible = false;
            this.btn_M_Help.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.btn_M_Help.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.btn_M_Help.ForeColor = SystemColors.ActiveCaption;
            this.btn_M_Help.Image = (Image) manager.GetObject("btn_M_Help.Image");
            this.btn_M_Help.ImageTransparentColor = Color.Magenta;
            this.btn_M_Help.Name = "btn_M_Help";
            this.btn_M_Help.Size = new Size(0x23, 0x16);
            this.btn_M_Help.Text = "帮助";
            this.toolStripSeparator7.Name = "toolStripSeparator7";
            this.toolStripSeparator7.Size = new Size(6, 0x19);
            this.colcWHId.DataPropertyName = "cWHId";
            this.colcWHId.FillWeight = 50f;
            this.colcWHId.Frozen = true;
            this.colcWHId.HeaderText = "仓库号";
            this.colcWHId.Name = "colcWHId";
            this.colcWHId.ReadOnly = true;
            this.colcWHId.ToolTipText = "仓库";
            this.colcWHId.Width = 110;
            this.grdList.AllowUserToAddRows = false;
            this.grdList.AllowUserToDeleteRows = false;
            this.grdList.AllowUserToOrderColumns = true;
            this.grdList.Columns.AddRange(new DataGridViewColumn[] { this.colcWHId, this.colcPltSpec, this.colcArea });
            this.grdList.EditMode = DataGridViewEditMode.EditProgrammatically;
            this.grdList.Location = new Point(12, 0x30);
            this.grdList.MultiSelect = false;
            this.grdList.Name = "grdList";
            this.grdList.ReadOnly = true;
            style.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style.BackColor = SystemColors.Control;
            style.Font = new Font("宋体", 9f, FontStyle.Bold, GraphicsUnit.Point, 0x86);
            style.ForeColor = SystemColors.WindowText;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            this.grdList.RowHeadersDefaultCellStyle = style;
            this.grdList.RowHeadersVisible = false;
            this.grdList.RowTemplate.Height = 0x17;
            this.grdList.Size = new Size(0x14d, 0x1b0);
            this.grdList.TabIndex = 13;
            this.grdList.Tag = "8";
            this.colcPltSpec.DataPropertyName = "cPltSpec";
            this.colcPltSpec.HeaderText = "托盘规格";
            this.colcPltSpec.Name = "colcPltSpec";
            this.colcPltSpec.ReadOnly = true;
            this.colcPltSpec.ToolTipText = "托盘规格";
            this.colcPltSpec.Width = 120;
            this.colcArea.DataPropertyName = "cAreaName";
            this.colcArea.HeaderText = "货区";
            this.colcArea.Name = "colcArea";
            this.colcArea.ReadOnly = true;
            this.colcArea.ToolTipText = "货区";
            this.tlb_M_New.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_New.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_New.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_New.Image = (Image) manager.GetObject("tlb_M_New.Image");
            this.tlb_M_New.ImageTransparentColor = Color.Magenta;
            this.tlb_M_New.Name = "tlb_M_New";
            this.tlb_M_New.Size = new Size(0x23, 0x16);
            this.tlb_M_New.Tag = "01";
            this.tlb_M_New.Text = "新建";
            this.tlb_M_New.Visible = false;
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new Size(6, 0x19);
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new Size(6, 0x19);
            this.tlb_M_Edit.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Edit.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Edit.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Edit.Image = (Image) manager.GetObject("tlb_M_Edit.Image");
            this.tlb_M_Edit.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Edit.Name = "tlb_M_Edit";
            this.tlb_M_Edit.Size = new Size(0x23, 0x16);
            this.tlb_M_Edit.Tag = "02";
            this.tlb_M_Edit.Text = "修改";
            this.pnlEdit.Controls.Add(this.label1);
            this.pnlEdit.Controls.Add(this.txt_nRow);
            this.pnlEdit.Controls.Add(this.label6);
            this.pnlEdit.Controls.Add(this.txt_cCarNo);
            this.pnlEdit.Controls.Add(this.cmb_cWHId);
            this.pnlEdit.Controls.Add(this.label3);
            this.pnlEdit.Location = new Point(0x15f, 0x30);
            this.pnlEdit.Name = "pnlEdit";
            this.pnlEdit.Size = new Size(0x1a8, 0x1b9);
            this.pnlEdit.TabIndex = 12;
            this.pnlEdit.Paint += new PaintEventHandler(this.pnlEdit_Paint);
            this.tlbMain.Items.AddRange(new ToolStripItem[] { 
                this.toolStripLabel1, this.toolStripSeparator2, this.toolStripSeparator1, this.tlb_M_New, this.tlb_M_Edit, this.toolStripSeparator3, this.tlb_M_Undo, this.tlb_M_Delete, this.toolStripSeparator4, this.tlb_M_Save, this.toolStripSeparator5, this.tlb_M_Refresh, this.tlb_M_Find, this.tlb_M_Print, this.toolStripSeparator6, this.tlb_M_Check, 
                this.tlb_M_UnCheck, this.toolStripSeparator7, this.btn_M_Help, this.tlb_M_Exit, this.toolStripSeparator8
             });
            this.tlbMain.Location = new Point(0, 0);
            this.tlbMain.Name = "tlbMain";
            this.tlbMain.Size = new Size(0x33a, 0x19);
            this.tlbMain.TabIndex = 11;
            this.tlbMain.Text = "toolStrip1";
            this.toolStripLabel1.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.toolStripLabel1.ForeColor = SystemColors.ActiveCaption;
            this.toolStripLabel1.Name = "toolStripLabel1";
            this.toolStripLabel1.Size = new Size(0, 0x16);
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new Size(6, 0x19);
            this.tlb_M_Undo.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Undo.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Undo.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Undo.Image = (Image) manager.GetObject("tlb_M_Undo.Image");
            this.tlb_M_Undo.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Undo.Name = "tlb_M_Undo";
            this.tlb_M_Undo.Size = new Size(0x23, 0x16);
            this.tlb_M_Undo.Tag = "03";
            this.tlb_M_Undo.Text = "取消";
            this.tlb_M_Delete.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Delete.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Delete.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Delete.Image = (Image) manager.GetObject("tlb_M_Delete.Image");
            this.tlb_M_Delete.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Delete.Name = "tlb_M_Delete";
            this.tlb_M_Delete.Size = new Size(0x23, 0x16);
            this.tlb_M_Delete.Tag = "04";
            this.tlb_M_Delete.Text = "删除";
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new Size(6, 0x19);
            this.tlb_M_Save.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Save.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Save.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Save.Image = (Image) manager.GetObject("tlb_M_Save.Image");
            this.tlb_M_Save.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Save.Name = "tlb_M_Save";
            this.tlb_M_Save.Size = new Size(0x23, 0x16);
            this.tlb_M_Save.Tag = "05";
            this.tlb_M_Save.Text = "保存";
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new Size(6, 0x19);
            this.tlb_M_Refresh.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Refresh.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Refresh.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Refresh.Image = (Image) manager.GetObject("tlb_M_Refresh.Image");
            this.tlb_M_Refresh.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Refresh.Name = "tlb_M_Refresh";
            this.tlb_M_Refresh.Size = new Size(0x23, 0x16);
            this.tlb_M_Refresh.Text = "刷新";
            this.tlb_M_Find.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Find.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Find.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Find.Image = (Image) manager.GetObject("tlb_M_Find.Image");
            this.tlb_M_Find.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Find.Name = "tlb_M_Find";
            this.tlb_M_Find.Size = new Size(0x23, 0x16);
            this.tlb_M_Find.Text = "查找";
            this.tlb_M_Find.Visible = false;
            this.tlb_M_Print.DisplayStyle = ToolStripItemDisplayStyle.Text;
            this.tlb_M_Print.Font = new Font("宋体", 9f, FontStyle.Bold);
            this.tlb_M_Print.ForeColor = SystemColors.ActiveCaption;
            this.tlb_M_Print.Image = (Image) manager.GetObject("tlb_M_Print.Image");
            this.tlb_M_Print.ImageTransparentColor = Color.Magenta;
            this.tlb_M_Print.Name = "tlb_M_Print";
            this.tlb_M_Print.Size = new Size(0x23, 0x16);
            this.tlb_M_Print.Tag = "06";
            this.tlb_M_Print.Text = "打印";
            this.tlb_M_Print.Visible = false;
            this.toolStripSeparator6.Name = "toolStripSeparator6";
            this.toolStripSeparator6.Size = new Size(6, 0x19);
            this.label6.AutoSize = true;
            this.label6.Location = new Point(0x19, 90);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x35, 12);
            this.label6.TabIndex = 0x12;
            this.label6.Text = "叉车号：";
            this.txt_cCarNo.BorderStyle = BorderStyle.FixedSingle;
            this.txt_cCarNo.Location = new Point(0x6d, 0x55);
            this.txt_cCarNo.Name = "txt_cCarNo";
            this.txt_cCarNo.ReadOnly = true;
            this.txt_cCarNo.Size = new Size(0x79, 0x15);
            this.txt_cCarNo.TabIndex = 0x11;
            this.txt_cCarNo.Tag = "0";
            this.txt_cCarNo.Text = "0";
            this.label1.AutoSize = true;
            this.label1.Location = new Point(0x19, 0x8d);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x29, 12);
            this.label1.TabIndex = 20;
            this.label1.Text = "排号：";
            this.txt_nRow.BorderStyle = BorderStyle.FixedSingle;
            this.txt_nRow.Location = new Point(0x6d, 0x88);
            this.txt_nRow.Name = "txt_nRow";
            this.txt_nRow.ReadOnly = true;
            this.txt_nRow.Size = new Size(0x79, 0x15);
            this.txt_nRow.TabIndex = 0x13;
            this.txt_nRow.Tag = "0";
            this.txt_nRow.Text = "0";
            base.AutoScaleDimensions = new SizeF(6f, 12f);
            base.ClientSize = new Size(0x33a, 0x21f);
            base.Controls.Add(this.grdList);
            base.Controls.Add(this.pnlEdit);
            base.Controls.Add(this.tlbMain);
            base.Name = "frmWCarRows";
            this.Text = "叉车巷道设置";
            ((ISupportInitialize) this.grdList).EndInit();
            this.pnlEdit.ResumeLayout(false);
            this.pnlEdit.PerformLayout();
            this.tlbMain.ResumeLayout(false);
            this.tlbMain.PerformLayout();
            base.ResumeLayout(false);
            base.PerformLayout();
        }

        private void pnlEdit_Paint(object sender, PaintEventArgs e)
        {
        }
    }
}

